name: Deploy

on:
  # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
  release:
    types: [published]

env:
  REACT_APP_PUBLIC_SURVEY_ENABLED: 'false'
  REACT_APP_API_URL: https://api.bostonhpa.org

jobs:
  deploy-server:
    uses: ./.github/workflows/deploy.yml
    with:
      app: bhpa-backend
      context: backend
      port: 3000
    secrets: inherit
  deploy-website:
    uses: ./.github/workflows/deploy.yml
    with:
      app: bhpa-frontend
      context: frontend/front
      port: 8080
    secrets:
      build-args: |
        REACT_APP_RECAPTCHA_KEY=${{ secrets.REACT_APP_RECAPTCHA_KEY }}
        REACT_APP_PUBLIC_SURVEY_ENABLED=${{ env.REACT_APP_PUBLIC_SURVEY_ENABLED }}
        REACT_APP_API_URL=${{ env.REACT_APP_API_URL }}
